######################################################################
# Copyright (c) 2020 Bosch.IO GmbH [and others]
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
########################################################################
{{if and .Values.components.certmanager.enabled .Values.components.ambassador.enabled .Values.dns.enabled}}
{{if or .Values.certificates.sslForTcpMappings .Values.certificates.sslForHttpMappings}}
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: {{.Release.Name}}-host
spec:
  hostname: {{.Values.dns.domain}}
  acmeProvider:
    authority: none
  tlsSecret:
    name: {{.Release.Name}}-tcp-certificate
{{end}}
{{end}}