######################################################################
# Copyright (c) 2019, 2020 Bosch.IO GmbH [and others]
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
########################################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-store-conf
type: Opaque
data:
  DEBUG: {{ printf "true" | b64enc}}
  APPSTORE_USERNAME: {{ .Values.appstore.credentials.username | b64enc}}
  APPSTORE_PASSWORD: {{ .Values.appstore.credentials.password | b64enc}}
  LOGGING_LEVEL_ORG_ECLIPSE_KUKSA: {{printf "DEBUG" | b64enc}}

  #TODO either use default or set value
  HAWKBIT_URL: {{printf "%s-hawkbit.%s.svc.cluster.local" .Release.Name .Release.Namespace | b64enc}}
  HAWKBIT_USERNAME: {{.Values.appstore.hawkbit.username | b64enc}}
  HAWKBIT_PASSWORD: {{.Values.appstore.hawkbit.password | b64enc}}

  SERVER_PORT: {{ printf "8080" | b64enc}} 
  SERVER_SERVLET_SESSION_COOKIE_NAME: {{ printf "APPSESSIONID" | b64enc}}
      
  SPRING_DATASOURCE_DRIVERCLASSNAME: {{ printf "org.h2.Driver" | b64enc}}
  SPRING_DATASOURCE_INITILIZATION-MODE: {{ printf "always" | b64enc}}
  SPRING_DATASOURCE_URL: {{ printf "jdbc:h2:file:/var/lib/kuksa/appstore-h2-database/appstore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE" | b64enc}}
  SPRING_H2_CONSOLE_ENABLED: {{ printf "false" | b64enc}}
  SPRING_H2_CONSOLE_PATH: {{ printf "/console" | b64enc}}
  SPRING_JPA_SHOW-SQL:  {{ printf "false" | b64enc}}
  SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: {{"true" | b64enc}}
  
  KEYCLOAK_REALM: {{.Values.appstore.keycloak.realm | b64enc }}
  KEYCLOAK_RESOURCE: {{ .Values.appstore.keycloak.resource | b64enc }}
  KEYCLOAK_AUTH-SERVER-URL: {{ .Values.appstore.keycloak.url | b64enc}}
  KEYCLOAK_SSL-REQUIRED: {{ "none" | b64enc }}
  KEYCLOAK_CREDENTIALS_SECRET: {{ .Values.appstore.keycloak.credentials.secret | b64enc }}
  KEYCLOAK_PRINCIPAL-ATTRIBUTE: {{ .Values.appstore.keycloak.principalAttribute | b64enc}}

  VAADIN_SERVLET_PRODUCTIONMODE: {{printf  .Values.appstore.vaadinProductionModeEnabled | b64enc}}