######################################################################
# Copyright (c) 2019, 2020 Bosch.IO GmbH [and others]
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
########################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Release.Name}}-app-store
    version: {{.Chart.AppVersion}}
  name: {{.Release.Name}}-app-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-app-store
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-app-store
        version: {{.Chart.AppVersion}}
    spec:
      containers:
      - name: appstore
        image: "{{ .Values.imageCredentials.registry }}/{{.Values.appstore.image}}:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8089
          name: redirect
          protocol: TCP
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/kuksa/
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-app-store-conf
        volumeMounts:
        - mountPath: /var/lib/kuksa/appstore-h2-database
          name: appstore-h2-database
        resources:
          requests:
            memory: "400Mi"
          limits:
            memory: "1Gi"
        imagePullPolicy: Always
      imagePullSecrets:
      - name: docker-secret
      volumes:
      - name: appstore-h2-database
        persistentVolumeClaim:
          claimName: appstore-h2-database