Vagrant.configure('2') do |config|
  config.vm.box = 'debian/bullseye64'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'debian_vm'
    vb.linked_clone = true
    vb.gui = false
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "install-kanto.sh"
end
